$(document).ready(function(){
    $('.wrap').slick({
        autoplay:true,
        slidesToShow:3,
        slidesToScroll:1,
        prevArrow:".pbtn",
        nextArrow:".nbtn",
        responsive:[
            {
                breakpoint:992,
                settings:{
                    slidesToShow:2,
                }
            },
            {
                breakpoint:768,
                settings:{
                    slidesToShow:1,
                }
            }
        ]
    })

    $('.trigger').click(function(){
        $('.contwrap').toggleClass('scale')
    })
})
